load("site.mat")
fq = 1.8e9; % 1.8GHz
txpower=38;  % watt
 

yagiAnt = design(yagiUda,fq);
% Tilt antenna to direct radiation in XY-plane (i.e. geographic azimuth)
yagiAnt.Tilt = 90;
yagiAnt.TiltAxis = 'y';
 
i=38;
% for i=1
%for i=1:length(Tx.site)

    tx=txsite('Name',Tx.nome(i),...
            'CoordinateSystem',"geographic",...
            'Latitude',Tx.site(i,1), ...
            'Longitude', Tx.site(i,2),...
            'Antenna',yagiAnt,...
            'AntennaAngle',0,...            
            'AntennaHeight',4,...%'AntennaPosition', [0;0;0],...
            'SystemLoss',0,...
            'TransmitterFrequency',fq, ...
            'TransmitterPower',txpower);

    tx2=txsite('Name',Tx.nome(i+1),...
            'Latitude',Tx.site(i+1,1), ...
            'Longitude', Tx.site(i+1,2),...
            'Antenna',yagiAnt,...
            'AntennaHeight',4,...            
            'TransmitterFrequency',fq, ...
            'TransmitterPower',txpower);

    tx.AntennaAngle=angle(tx,tx2);
    tx2.AntennaAngle=angle(tx2,tx);
    coverage(tx, 'SignalStrengths',-100:5:-60) 
    coverage(tx2, 'SignalStrengths',-100:5:-60)
% end